### PR TITLE
HW1 SHELL

### PR DESCRIPTION
**Pull request by Mikhail-M**

### CODE REVIEW

**Review by krinkin — CHANGES_REQUESTED** [review]
wrong solution path

**Comment by Mikhail-M** [comment]
Fixed

**Comment by krinkin** [comment]
Please split pull requests by labs. One lab - one pull request

**Comment by krinkin** [comment]
samples/shell/sh.c is still in pull request

**Comment by Mikhail-M** [comment]
Can I close this and create new, without trash?

**Pull request closed without merging**
